"""autogenerated by genmsg_py from SystemDescription.msg. Do not edit."""
import roslib.message
import struct


class SystemDescription(roslib.message.Message):
  _md5sum = "367459a5d65a9e456af927b052e15768"
  _type = "diagnosis_msgs/SystemDescription"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 out_time
string[] rules
string[] props
string AB
string NAB
string neg_prefix

"""
  __slots__ = ['out_time','rules','props','AB','NAB','neg_prefix']
  _slot_types = ['float32','string[]','string[]','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       out_time,rules,props,AB,NAB,neg_prefix
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SystemDescription, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.out_time is None:
        self.out_time = 0.
      if self.rules is None:
        self.rules = []
      if self.props is None:
        self.props = []
      if self.AB is None:
        self.AB = ''
      if self.NAB is None:
        self.NAB = ''
      if self.neg_prefix is None:
        self.neg_prefix = ''
    else:
      self.out_time = 0.
      self.rules = []
      self.props = []
      self.AB = ''
      self.NAB = ''
      self.neg_prefix = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      buff.write(_struct_f.pack(self.out_time))
      length = len(self.rules)
      buff.write(_struct_I.pack(length))
      for val1 in self.rules:
        length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.props)
      buff.write(_struct_I.pack(length))
      for val1 in self.props:
        length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.AB
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.NAB
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.neg_prefix
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (self.out_time,) = _struct_f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.rules = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1 = str[start:end]
        self.rules.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.props = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1 = str[start:end]
        self.props.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.AB = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.NAB = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.neg_prefix = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      buff.write(_struct_f.pack(self.out_time))
      length = len(self.rules)
      buff.write(_struct_I.pack(length))
      for val1 in self.rules:
        length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      length = len(self.props)
      buff.write(_struct_I.pack(length))
      for val1 in self.props:
        length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.AB
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.NAB
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.neg_prefix
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.out_time,) = _struct_f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.rules = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1 = str[start:end]
        self.rules.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.props = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1 = str[start:end]
        self.props.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.AB = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.NAB = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.neg_prefix = str[start:end]
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_f = struct.Struct("<f")
